// Include section for the header ffiles
#include <time.h>
#include <stdlib.h>
#include <stdio.h>

// Define section
#define MAX_NUM 100    // The maximum number generated by the computer
#define INCREASE_NUM 1 // To increase the range of the generated number

// Start of the main function
int main()
{
    // Section for the variable declaration
    int userAnswer;     // Answer provided by the user
    int numOfGuess = 1; // Number of guesses made by the user
    int playAgain = 1;  // User's input for playing the game again
    int answer;         // Answer generated by the computer

    // Loop that runs while the user wants to play the game
    while (playAgain != 0)
    {
        // Declare time to be null to give different outcome whenever the code runs again
        srand(time(NULL));
        // Store random number generated by the computer to the answer variable
        answer = rand() % MAX_NUM + INCREASE_NUM;

        printf("Type in your estimate: ");
        // Receive the user's input and store it at the userAnswer
        scanf("%d", &userAnswer);
        // Run the loop while the answer provided by the user does not match the answer
        while (userAnswer != answer)
        {
            // If the user's answer is larger than the answer
            if (userAnswer > answer)
            {
                printf("Your guess is too high: ");
                // Get a new input from the user and save it in the user's answer
                scanf("%d", &userAnswer);
                // Increase the number of guesses
                numOfGuess++;
            }
            // If the user's answer is smaller than the answer
            if (userAnswer < answer)
            {
                printf("Your guess is too low: ");
                // Get a new input from the user and save it in the user's answer
                scanf("%d", &userAnswer);
                // Increase the number of guesses
                numOfGuess++;
            }

            // If the user types in a number larger than the MAX_NUM, exit the program
            if (userAnswer > MAX_NUM)
            {
                // Return 0 to exit the program
                return 0;
            }
        }
        // If the userAnswer equals to the real answer, return the number of guesses made
        if (userAnswer == answer)
        {
            printf("You have guessed %d times and your guess is correct! \n", numOfGuess);
        }
        // If else, exit the program
        else
        {
            printf("Exiting the program. \n");
        }

        printf("Would you like to play again? Type 1 for yes and 0 for no: ");
        // See if the user wants to play the game again
        scanf("%d", &playAgain);
        // Reset the number of guess back to 1
        numOfGuess = 1;
    }

    // Return 0 to exit the code
    return 0;
}
